### ISSUE TITLE
io.UnsupportedOppration emerges

### ISSUE THREAD

**Issue by tarohi24** [antonisa/lang2vec#1]
When I ran the following code, I got `io.UnsupportedOperation: seek`.
```python
import lang2vec.lang2vec as l2v
l2v.distance('syntactic', 'eng', 'fra')
```

The stack trace is below:
```
Traceback (most recent call last):
  File "a.py", line 4, in <module>
    l2v.distance('syntactic', 'eng', 'fra')
  File "/home/ubuntu/cross-lingual-embedding/lang2vec/lang2vec.py", line 401, in distance
    data = sparse.load_npz(zp.open(map_distance_to_filename(dist)))
  File "/home/ubuntu/anaconda3/envs/pt/lib/python3.6/site-packages/scipy/sparse/_matrix_io.py", line 131, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/home/ubuntu/anaconda3/envs/pt/lib/python3.6/site-packages/numpy/lib/npyio.py", line 426, in load
    fid.seek(-min(N, len(magic)), 1)  # back-up
io.UnsupportedOperation: seek
```

Do you have any ideas to fix the issue?

My environment:
- Python 3.6.8
- Anaconda 3
- lang2vec version: https://github.com/antonisa/lang2vec/commit/82ab4457ae3a45f552b8d70310ac2a259b44c62a

**Comment by antonisa** [comment]
Hmmm this seems like a scipy/numpy version problem.
I downloaded and installed lang2vec in a clean virtualenv and I was able to run it properly.
For reference, I am using 
- Python 3.7.2
- numpy 1.16.2
- scipy 1.2.1

Alternatively, can you try maybe installing with pip as follows?
(the distance computation is still in the testing phase)
`pip install -i https://test.pypi.org/simple/ lang2vec`

let me know how it goes!

**Comment by tarohi24** [comment]
Thank you for replying and sorry for not having mentioned versions of packages.
I tried Python 3.7.2 instead of 3.6.8. Then the program works!
I am using the same version numpy/scipy.

Thank you!
