### ISSUE TITLE
'distance' method doesn't work with pip installation

### ISSUE THREAD

**Issue by VinuraD** [antonisa/lang2vec#11]
When I install the lib with pip (in a conda environment), it throws an error `AttributeError: module 'lang2vec.lang2vec' has no attribute 'distance'`. When installed with setup tools, it works fine.

**Comment by erzaliator** [comment]
Get the same error while trying to access syntactic_distance(). `AttributeError: module 'lang2vec.lang2vec' has no attribute 'syntactic_distance'`

Upon further inspection my installation of lang2vec==1.1.2 shows missing definitions of geographic_distance, syntactic_distance, etc. Basically the file (lang2vec/lang2vec.py) seems outdated and wrong. I will be cloning the repo. But it is strange that the pip installation files don't match with the repo.

**Comment by antonisa** [comment]
Yes, sorry -- the problem is that the pip installation required that I uploaded the distance files in pip. But it is too big to be shared through that. So if you need to use the distance functions you need to install from source, apologies.

**Comment by erzaliator** [comment]
Thank you for the information @antonisa ! 
And yes, cloning the repo works as promised.
