### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by Ming-H** [antonisa/lang2vec#5]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/data/letter_codes.json'

**Comment by antonisa** [comment]
Hi, how did you install?
Did you use pip or install from source?
What are the commands you ran?

**Comment by kellymarchisio** [comment]
For posterity, I just saw this error.  

To reproduce, install via:
```
git clone https://github.com/antonisa/lang2vec
cd lang2vec
python3 setup.py install
```
From there, I _think_ I did (without cd-ing back): run __python__, then `import lang2vec as l2v` results in `[Errno 20] Not a directory:....letter_codes.json'`

However, then I cd-ed back to the higher-level directory and imported as `import lang2vec.lang2vec as l2v`, it worked.  And now it works everywhere.
