### ISSUE TITLE
Both ways of install do not work

### ISSUE THREAD

**Issue by houwenxin** [antonisa/lang2vec#6]
when using pip install, there is no "distance" attribute problem.

> AttributeError: module 'lang2vec.lang2vec' has no attribute 'distance'

when using setup.py, there is decode error.

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9750: ordinal not in range(128)

**Comment by antonisa** [comment]
Hi,
could you share the exact code that returns these errors?
(Re the first error: You need to install from source in order to use the `distance` function)

**Comment by houwenxin** [comment]
I have re-installed the librirary. It now works, thank you very much!
